/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdad8",
        "error-container": "#ffdad6",
        "surface-tint": "#a83729",
        "primary-fixed-dim": "#ffb4a8",
        "secondary-fixed-dim": "#ffb3b1",
        "on-surface": "#1c1c19",
        "surface": "#fcf9f4",
        "secondary": "#a13c3f",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline-variant": "#dfbfba",
        "surface-container-low": "#f6f3ee",
        "surface-bright": "#fcf9f4",
        "surface-dim": "#dcdad5",
        "inverse-primary": "#ffb4a8",
        "inverse-on-surface": "#f3f0eb",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-background": "#1c1c19",
        "secondary-container": "#ff8484",
        "tertiary-fixed": "#ffdcc5",
        "outline": "#8b716d",
        "surface-container-highest": "#e5e2dd",
        "primary-fixed": "#ffdad4",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fff3ed",
        "tertiary-fixed-dim": "#f4bb92",
        "on-primary-fixed": "#410000",
        "primary-container": "#c04838",
        "on-surface-variant": "#58413e",
        "on-tertiary-fixed": "#301400",
        "on-secondary-fixed-variant": "#82252a",
        "surface-container": "#f0ede8",
        "on-primary-fixed-variant": "#881f14",
        "background": "#fcf9f4",
        "on-primary-container": "#fff2f0",
        "surface-container-high": "#ebe8e3",
        "tertiary-container": "#946643",
        "tertiary": "#784e2d",
        "surface-variant": "#e5e2dd",
        "primary": "#9f3023",
        "inverse-surface": "#31302d",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#751c22",
        "on-secondary-fixed": "#410007",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#653d1e"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
